/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */
import { Plugin } from '@nocobase/client';
import { Registry } from '@nocobase/utils/client';
import { Instruction } from './nodes';
import { Trigger } from './triggers';
import { VariableOption } from './variable';
import { TaskTypeOptions } from './WorkflowTasks';
import { NodeDetailsModel, NodeValueModel } from './models';
type InstructionGroup = {
    key?: string;
    label: string;
};
export default class PluginWorkflowClient extends Plugin {
    triggers: Registry<Trigger>;
    instructions: Registry<Instruction>;
    instructionGroups: Registry<InstructionGroup>;
    systemVariables: Registry<VariableOption>;
    taskTypes: Registry<TaskTypeOptions>;
    useTriggersOptions: () => {
        value: string;
        label: any;
        color: string;
        options: {
            sync: boolean;
            description?: string;
            fieldset: Record<string, import("@formily/json-schema").Stringify<{
                [key: symbol]: any;
                [key: `x-${string}`]: any;
                [key: `x-${number}`]: any;
                version?: string;
                name?: import("@formily/json-schema").SchemaKey;
                title?: any;
                description?: any;
                default?: any;
                readOnly?: boolean;
                writeOnly?: boolean;
                type?: import("@formily/json-schema").SchemaTypes;
                enum?: import("@formily/json-schema").SchemaEnum<any>;
                const?: any;
                multipleOf?: number;
                maximum?: number;
                exclusiveMaximum?: number;
                minimum?: number;
                exclusiveMinimum?: number;
                maxLength?: number;
                minLength?: number;
                pattern?: string | RegExp;
                maxItems?: number;
                minItems?: number;
                uniqueItems?: boolean;
                maxProperties?: number;
                minProperties?: number;
                required?: string | boolean | string[];
                format?: string;
                $ref?: string;
                $namespace?: string;
                definitions?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                properties?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                items?: import("@formily/json-schema").SchemaItems<any, any, any, any, any, any, any, any>;
                additionalItems?: import("@formily/json-schema").Stringify<any>;
                patternProperties?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                additionalProperties?: import("@formily/json-schema").Stringify<any>;
                "x-value"?: any;
                "x-index"?: number;
                "x-pattern"?: any;
                "x-display"?: any;
                "x-validator"?: any;
                "x-decorator"?: any;
                "x-decorator-props"?: any;
                "x-component"?: any;
                "x-component-props"?: any;
                "x-reactions"?: import("@formily/json-schema").SchemaReactions<any>;
                "x-content"?: any;
                "x-data"?: any;
                "x-visible"?: boolean;
                "x-hidden"?: boolean;
                "x-disabled"?: boolean;
                "x-editable"?: boolean;
                "x-read-only"?: boolean;
                "x-read-pretty"?: boolean;
                "x-compile-omitted"?: string[];
            }>>;
            triggerFieldset?: Record<string, import("@formily/json-schema").Stringify<{
                [key: symbol]: any;
                [key: `x-${string}`]: any;
                [key: `x-${number}`]: any;
                version?: string;
                name?: import("@formily/json-schema").SchemaKey;
                title?: any;
                description?: any;
                default?: any;
                readOnly?: boolean;
                writeOnly?: boolean;
                type?: import("@formily/json-schema").SchemaTypes;
                enum?: import("@formily/json-schema").SchemaEnum<any>;
                const?: any;
                multipleOf?: number;
                maximum?: number;
                exclusiveMaximum?: number;
                minimum?: number;
                exclusiveMinimum?: number;
                maxLength?: number;
                minLength?: number;
                pattern?: string | RegExp;
                maxItems?: number;
                minItems?: number;
                uniqueItems?: boolean;
                maxProperties?: number;
                minProperties?: number;
                required?: string | boolean | string[];
                format?: string;
                $ref?: string;
                $namespace?: string;
                definitions?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                properties?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                items?: import("@formily/json-schema").SchemaItems<any, any, any, any, any, any, any, any>;
                additionalItems?: import("@formily/json-schema").Stringify<any>;
                patternProperties?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                additionalProperties?: import("@formily/json-schema").Stringify<any>;
                "x-value"?: any;
                "x-index"?: number;
                "x-pattern"?: any;
                "x-display"?: any;
                "x-validator"?: any;
                "x-decorator"?: any;
                "x-decorator-props"?: any;
                "x-component"?: any;
                "x-component-props"?: any;
                "x-reactions"?: import("@formily/json-schema").SchemaReactions<any>;
                "x-content"?: any;
                "x-data"?: any;
                "x-visible"?: boolean;
                "x-hidden"?: boolean;
                "x-disabled"?: boolean;
                "x-editable"?: boolean;
                "x-read-only"?: boolean;
                "x-read-pretty"?: boolean;
                "x-compile-omitted"?: string[];
            }>>;
            view?: import("@formily/json-schema").Stringify<{
                [key: symbol]: any;
                [key: `x-${string}`]: any;
                [key: `x-${number}`]: any;
                version?: string;
                name?: import("@formily/json-schema").SchemaKey;
                title?: any;
                description?: any;
                default?: any;
                readOnly?: boolean;
                writeOnly?: boolean;
                type?: import("@formily/json-schema").SchemaTypes;
                enum?: import("@formily/json-schema").SchemaEnum<any>;
                const?: any;
                multipleOf?: number;
                maximum?: number;
                exclusiveMaximum?: number;
                minimum?: number;
                exclusiveMinimum?: number;
                maxLength?: number;
                minLength?: number;
                pattern?: string | RegExp;
                maxItems?: number;
                minItems?: number;
                uniqueItems?: boolean;
                maxProperties?: number;
                minProperties?: number;
                required?: string | boolean | string[];
                format?: string;
                $ref?: string;
                $namespace?: string;
                definitions?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                properties?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                items?: import("@formily/json-schema").SchemaItems<any, any, any, any, any, any, any, any>;
                additionalItems?: import("@formily/json-schema").Stringify<any>;
                patternProperties?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                additionalProperties?: import("@formily/json-schema").Stringify<any>;
                "x-value"?: any;
                "x-index"?: number;
                "x-pattern"?: any;
                "x-display"?: any;
                "x-validator"?: any;
                "x-decorator"?: any;
                "x-decorator-props"?: any;
                "x-component"?: any;
                "x-component-props"?: any;
                "x-reactions"?: import("@formily/json-schema").SchemaReactions<any>;
                "x-content"?: any;
                "x-data"?: any;
                "x-visible"?: boolean;
                "x-hidden"?: boolean;
                "x-disabled"?: boolean;
                "x-editable"?: boolean;
                "x-read-only"?: boolean;
                "x-read-pretty"?: boolean;
                "x-compile-omitted"?: string[];
            }>;
            scope?: {
                [key: string]: any;
            };
            components?: {
                [key: string]: any;
            };
            initializers?: any;
            isActionTriggerable_deprecated?: boolean | ((config: object, context?: object) => boolean);
        };
    }[];
    useInstructionGroupOptions: () => {
        key: string;
        label: any;
    }[];
    isWorkflowSync(workflow: any): any;
    registerTrigger(type: string, trigger: Trigger | {
        new (): Trigger;
    }): void;
    registerInstruction(type: string, instruction: Instruction | {
        new (): Instruction;
    }): void;
    registerInstructionGroup(key: string, group: InstructionGroup): void;
    registerSystemVariable(option: VariableOption): void;
    registerTaskType(key: string, option: TaskTypeOptions): void;
    registerCollectionsToDataSource(collectionOptions: any[]): void;
    load(): Promise<void>;
}
export * from './Branch';
export * from './components';
export * from './constants';
export * from './ExecutionContextProvider';
export * from './FlowContext';
export * from './hooks';
export * from './nodes';
export * from './settings/BindWorkflowConfig';
export { default as useStyles } from './style';
export { Trigger, useTrigger } from './triggers';
export * from './utils';
export * from './variable';
export { usePopupRecordContext, useTasksCountsContext } from './WorkflowTasks';
export { createTriggerWorkflowsSchema } from './flows/triggerWorkflows';
export { NodeDetailsModel, NodeValueModel };
