/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */
import { CollectionFieldInterface } from '@nocobase/client';
export declare class FormulaFieldInterface extends CollectionFieldInterface {
    name: string;
    type: string;
    group: string;
    order: number;
    title: string;
    description: string;
    sortable: boolean;
    default: {
        type: string;
        uiSchema: {
            type: string;
            'x-component': string;
            'x-component-props': {
                stringMode: boolean;
                step: string;
            };
            'x-read-pretty': boolean;
        };
    };
    properties: {
        engine: {
            type: string;
            title: string;
            'x-decorator': string;
            'x-component': string;
            enum: any[];
            required: boolean;
            default: string;
        };
        expression: {
            type: string;
            title: string;
            required: boolean;
            'x-component': string;
            'x-decorator': string;
            'x-component-props': {
                useCurrentFields: string;
            };
            'x-reactions': {
                dependencies: string[];
                fulfill: {
                    schema: {
                        description: string;
                    };
                };
            };
        };
        'uiSchema.x-component-props.dateFormat': {
            'x-reactions': {
                dependencies: string[];
                fulfill: {
                    state: {
                        display: string;
                    };
                };
            }[];
            version?: string | (string & {});
            name?: (string & {}) | import("@formily/json-schema").SchemaKey;
            title?: any;
            description?: any;
            default?: any;
            readOnly?: boolean | (string & {});
            writeOnly?: boolean | (string & {});
            type?: import("@formily/json-schema").SchemaTypes;
            enum?: (string & {}) | import("@formily/json-schema").SchemaEnum<any>;
            const?: any;
            multipleOf?: number | (string & {});
            maximum?: number | (string & {});
            exclusiveMaximum?: number | (string & {});
            minimum?: number | (string & {});
            exclusiveMinimum?: number | (string & {});
            maxLength?: number | (string & {});
            minLength?: number | (string & {});
            pattern?: string | RegExp | (string & {});
            maxItems?: number | (string & {});
            minItems?: number | (string & {});
            uniqueItems?: boolean | (string & {});
            maxProperties?: number | (string & {});
            minProperties?: number | (string & {});
            required?: string | boolean | string[] | (string & {});
            format?: string | (string & {});
            $ref?: string | (string & {});
            $namespace?: string | (string & {});
            definitions?: (string & {}) | import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
            properties?: (string & {}) | import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
            items?: (string & {}) | import("@formily/json-schema").SchemaItems<any, any, any, any, any, any, any, any>;
            additionalItems?: (string & {}) | import("@formily/json-schema").Stringify<{
                [key: symbol]: any;
                [key: `x-${string}`]: any;
                [key: `x-${number}`]: any;
                version?: string;
                name?: import("@formily/json-schema").SchemaKey;
                title?: any;
                description?: any;
                default?: any;
                readOnly?: boolean;
                writeOnly?: boolean;
                type?: import("@formily/json-schema").SchemaTypes;
                enum?: import("@formily/json-schema").SchemaEnum<any>;
                const?: any;
                multipleOf?: number;
                maximum?: number;
                exclusiveMaximum?: number;
                minimum?: number;
                exclusiveMinimum?: number;
                maxLength?: number;
                minLength?: number;
                pattern?: string | RegExp;
                maxItems?: number;
                minItems?: number;
                uniqueItems?: boolean;
                maxProperties?: number;
                minProperties?: number;
                required?: string | boolean | string[];
                format?: string;
                $ref?: string;
                $namespace?: string;
                definitions?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                properties?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                items?: import("@formily/json-schema").SchemaItems<any, any, any, any, any, any, any, any>;
                additionalItems?: import("@formily/json-schema").Stringify<any>;
                patternProperties?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                additionalProperties?: import("@formily/json-schema").Stringify<any>;
                "x-value"?: any;
                "x-index"?: number;
                "x-pattern"?: any;
                "x-display"?: any;
                "x-validator"?: any;
                "x-decorator"?: any;
                "x-decorator-props"?: any;
                "x-component"?: any;
                "x-component-props"?: any;
                "x-reactions"?: import("@formily/json-schema").SchemaReactions<any>;
                "x-content"?: any;
                "x-data"?: any;
                "x-visible"?: boolean;
                "x-hidden"?: boolean;
                "x-disabled"?: boolean;
                "x-editable"?: boolean;
                "x-read-only"?: boolean;
                "x-read-pretty"?: boolean;
                "x-compile-omitted"?: string[];
            }>;
            patternProperties?: (string & {}) | import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
            additionalProperties?: (string & {}) | import("@formily/json-schema").Stringify<{
                [key: symbol]: any;
                [key: `x-${string}`]: any;
                [key: `x-${number}`]: any;
                version?: string;
                name?: import("@formily/json-schema").SchemaKey;
                title?: any;
                description?: any;
                default?: any;
                readOnly?: boolean;
                writeOnly?: boolean;
                type?: import("@formily/json-schema").SchemaTypes;
                enum?: import("@formily/json-schema").SchemaEnum<any>;
                const?: any;
                multipleOf?: number;
                maximum?: number;
                exclusiveMaximum?: number;
                minimum?: number;
                exclusiveMinimum?: number;
                maxLength?: number;
                minLength?: number;
                pattern?: string | RegExp;
                maxItems?: number;
                minItems?: number;
                uniqueItems?: boolean;
                maxProperties?: number;
                minProperties?: number;
                required?: string | boolean | string[];
                format?: string;
                $ref?: string;
                $namespace?: string;
                definitions?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                properties?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                items?: import("@formily/json-schema").SchemaItems<any, any, any, any, any, any, any, any>;
                additionalItems?: import("@formily/json-schema").Stringify<any>;
                patternProperties?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                additionalProperties?: import("@formily/json-schema").Stringify<any>;
                "x-value"?: any;
                "x-index"?: number;
                "x-pattern"?: any;
                "x-display"?: any;
                "x-validator"?: any;
                "x-decorator"?: any;
                "x-decorator-props"?: any;
                "x-component"?: any;
                "x-component-props"?: any;
                "x-reactions"?: import("@formily/json-schema").SchemaReactions<any>;
                "x-content"?: any;
                "x-data"?: any;
                "x-visible"?: boolean;
                "x-hidden"?: boolean;
                "x-disabled"?: boolean;
                "x-editable"?: boolean;
                "x-read-only"?: boolean;
                "x-read-pretty"?: boolean;
                "x-compile-omitted"?: string[];
            }>;
            "x-value"?: any;
            "x-index"?: number | (string & {});
            "x-pattern"?: any;
            "x-display"?: any;
            "x-validator"?: any;
            "x-decorator"?: any;
            "x-decorator-props"?: any;
            "x-component"?: any;
            "x-component-props"?: any;
            "x-content"?: any;
            "x-data"?: any;
            "x-visible"?: boolean | (string & {});
            "x-hidden"?: boolean | (string & {});
            "x-disabled"?: boolean | (string & {});
            "x-editable"?: boolean | (string & {});
            "x-read-only"?: boolean | (string & {});
            "x-read-pretty"?: boolean | (string & {});
            "x-compile-omitted"?: string[] | (string & {});
        };
        'uiSchema.x-component-props.showTime': {
            'x-reactions': (string | {
                dependencies: string[];
                fulfill: {
                    state: {
                        display: string;
                    };
                };
            })[];
            version?: string | (string & {});
            name?: (string & {}) | import("@formily/json-schema").SchemaKey;
            title?: any;
            description?: any;
            default?: any;
            readOnly?: boolean | (string & {});
            writeOnly?: boolean | (string & {});
            type?: import("@formily/json-schema").SchemaTypes;
            enum?: (string & {}) | import("@formily/json-schema").SchemaEnum<any>;
            const?: any;
            multipleOf?: number | (string & {});
            maximum?: number | (string & {});
            exclusiveMaximum?: number | (string & {});
            minimum?: number | (string & {});
            exclusiveMinimum?: number | (string & {});
            maxLength?: number | (string & {});
            minLength?: number | (string & {});
            pattern?: string | RegExp | (string & {});
            maxItems?: number | (string & {});
            minItems?: number | (string & {});
            uniqueItems?: boolean | (string & {});
            maxProperties?: number | (string & {});
            minProperties?: number | (string & {});
            required?: string | boolean | string[] | (string & {});
            format?: string | (string & {});
            $ref?: string | (string & {});
            $namespace?: string | (string & {});
            definitions?: (string & {}) | import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
            properties?: (string & {}) | import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
            items?: (string & {}) | import("@formily/json-schema").SchemaItems<any, any, any, any, any, any, any, any>;
            additionalItems?: (string & {}) | import("@formily/json-schema").Stringify<{
                [key: symbol]: any;
                [key: `x-${string}`]: any;
                [key: `x-${number}`]: any;
                version?: string;
                name?: import("@formily/json-schema").SchemaKey;
                title?: any;
                description?: any;
                default?: any;
                readOnly?: boolean;
                writeOnly?: boolean;
                type?: import("@formily/json-schema").SchemaTypes;
                enum?: import("@formily/json-schema").SchemaEnum<any>;
                const?: any;
                multipleOf?: number;
                maximum?: number;
                exclusiveMaximum?: number;
                minimum?: number;
                exclusiveMinimum?: number;
                maxLength?: number;
                minLength?: number;
                pattern?: string | RegExp;
                maxItems?: number;
                minItems?: number;
                uniqueItems?: boolean;
                maxProperties?: number;
                minProperties?: number;
                required?: string | boolean | string[];
                format?: string;
                $ref?: string;
                $namespace?: string;
                definitions?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                properties?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                items?: import("@formily/json-schema").SchemaItems<any, any, any, any, any, any, any, any>;
                additionalItems?: import("@formily/json-schema").Stringify<any>;
                patternProperties?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                additionalProperties?: import("@formily/json-schema").Stringify<any>;
                "x-value"?: any;
                "x-index"?: number;
                "x-pattern"?: any;
                "x-display"?: any;
                "x-validator"?: any;
                "x-decorator"?: any;
                "x-decorator-props"?: any;
                "x-component"?: any;
                "x-component-props"?: any;
                "x-reactions"?: import("@formily/json-schema").SchemaReactions<any>;
                "x-content"?: any;
                "x-data"?: any;
                "x-visible"?: boolean;
                "x-hidden"?: boolean;
                "x-disabled"?: boolean;
                "x-editable"?: boolean;
                "x-read-only"?: boolean;
                "x-read-pretty"?: boolean;
                "x-compile-omitted"?: string[];
            }>;
            patternProperties?: (string & {}) | import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
            additionalProperties?: (string & {}) | import("@formily/json-schema").Stringify<{
                [key: symbol]: any;
                [key: `x-${string}`]: any;
                [key: `x-${number}`]: any;
                version?: string;
                name?: import("@formily/json-schema").SchemaKey;
                title?: any;
                description?: any;
                default?: any;
                readOnly?: boolean;
                writeOnly?: boolean;
                type?: import("@formily/json-schema").SchemaTypes;
                enum?: import("@formily/json-schema").SchemaEnum<any>;
                const?: any;
                multipleOf?: number;
                maximum?: number;
                exclusiveMaximum?: number;
                minimum?: number;
                exclusiveMinimum?: number;
                maxLength?: number;
                minLength?: number;
                pattern?: string | RegExp;
                maxItems?: number;
                minItems?: number;
                uniqueItems?: boolean;
                maxProperties?: number;
                minProperties?: number;
                required?: string | boolean | string[];
                format?: string;
                $ref?: string;
                $namespace?: string;
                definitions?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                properties?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                items?: import("@formily/json-schema").SchemaItems<any, any, any, any, any, any, any, any>;
                additionalItems?: import("@formily/json-schema").Stringify<any>;
                patternProperties?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                additionalProperties?: import("@formily/json-schema").Stringify<any>;
                "x-value"?: any;
                "x-index"?: number;
                "x-pattern"?: any;
                "x-display"?: any;
                "x-validator"?: any;
                "x-decorator"?: any;
                "x-decorator-props"?: any;
                "x-component"?: any;
                "x-component-props"?: any;
                "x-reactions"?: import("@formily/json-schema").SchemaReactions<any>;
                "x-content"?: any;
                "x-data"?: any;
                "x-visible"?: boolean;
                "x-hidden"?: boolean;
                "x-disabled"?: boolean;
                "x-editable"?: boolean;
                "x-read-only"?: boolean;
                "x-read-pretty"?: boolean;
                "x-compile-omitted"?: string[];
            }>;
            "x-value"?: any;
            "x-index"?: number | (string & {});
            "x-pattern"?: any;
            "x-display"?: any;
            "x-validator"?: any;
            "x-decorator"?: any;
            "x-decorator-props"?: any;
            "x-component"?: any;
            "x-component-props"?: any;
            "x-content"?: any;
            "x-data"?: any;
            "x-visible"?: boolean | (string & {});
            "x-hidden"?: boolean | (string & {});
            "x-disabled"?: boolean | (string & {});
            "x-editable"?: boolean | (string & {});
            "x-read-only"?: boolean | (string & {});
            "x-read-pretty"?: boolean | (string & {});
            "x-compile-omitted"?: string[] | (string & {});
        };
        'uiSchema.x-component-props.timeFormat': {
            [x: symbol]: any;
            [x: `x-${string}`]: any;
            [x: `x-${number}`]: any;
            version?: string | (string & {});
            name?: (string & {}) | import("@formily/json-schema").SchemaKey;
            title?: any;
            description?: any;
            default?: any;
            readOnly?: boolean | (string & {});
            writeOnly?: boolean | (string & {});
            type?: import("@formily/json-schema").SchemaTypes;
            enum?: (string & {}) | import("@formily/json-schema").SchemaEnum<any>;
            const?: any;
            multipleOf?: number | (string & {});
            maximum?: number | (string & {});
            exclusiveMaximum?: number | (string & {});
            minimum?: number | (string & {});
            exclusiveMinimum?: number | (string & {});
            maxLength?: number | (string & {});
            minLength?: number | (string & {});
            pattern?: string | RegExp | (string & {});
            maxItems?: number | (string & {});
            minItems?: number | (string & {});
            uniqueItems?: boolean | (string & {});
            maxProperties?: number | (string & {});
            minProperties?: number | (string & {});
            required?: string | boolean | string[] | (string & {});
            format?: string | (string & {});
            $ref?: string | (string & {});
            $namespace?: string | (string & {});
            definitions?: (string & {}) | import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
            properties?: (string & {}) | import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
            items?: (string & {}) | import("@formily/json-schema").SchemaItems<any, any, any, any, any, any, any, any>;
            additionalItems?: (string & {}) | import("@formily/json-schema").Stringify<{
                [key: symbol]: any;
                [key: `x-${string}`]: any;
                [key: `x-${number}`]: any;
                version?: string;
                name?: import("@formily/json-schema").SchemaKey;
                title?: any;
                description?: any;
                default?: any;
                readOnly?: boolean;
                writeOnly?: boolean;
                type?: import("@formily/json-schema").SchemaTypes;
                enum?: import("@formily/json-schema").SchemaEnum<any>;
                const?: any;
                multipleOf?: number;
                maximum?: number;
                exclusiveMaximum?: number;
                minimum?: number;
                exclusiveMinimum?: number;
                maxLength?: number;
                minLength?: number;
                pattern?: string | RegExp;
                maxItems?: number;
                minItems?: number;
                uniqueItems?: boolean;
                maxProperties?: number;
                minProperties?: number;
                required?: string | boolean | string[];
                format?: string;
                $ref?: string;
                $namespace?: string;
                definitions?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                properties?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                items?: import("@formily/json-schema").SchemaItems<any, any, any, any, any, any, any, any>;
                additionalItems?: import("@formily/json-schema").Stringify<any>;
                patternProperties?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                additionalProperties?: import("@formily/json-schema").Stringify<any>;
                "x-value"?: any;
                "x-index"?: number;
                "x-pattern"?: any;
                "x-display"?: any;
                "x-validator"?: any;
                "x-decorator"?: any;
                "x-decorator-props"?: any;
                "x-component"?: any;
                "x-component-props"?: any;
                "x-reactions"?: import("@formily/json-schema").SchemaReactions<any>;
                "x-content"?: any;
                "x-data"?: any;
                "x-visible"?: boolean;
                "x-hidden"?: boolean;
                "x-disabled"?: boolean;
                "x-editable"?: boolean;
                "x-read-only"?: boolean;
                "x-read-pretty"?: boolean;
                "x-compile-omitted"?: string[];
            }>;
            patternProperties?: (string & {}) | import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
            additionalProperties?: (string & {}) | import("@formily/json-schema").Stringify<{
                [key: symbol]: any;
                [key: `x-${string}`]: any;
                [key: `x-${number}`]: any;
                version?: string;
                name?: import("@formily/json-schema").SchemaKey;
                title?: any;
                description?: any;
                default?: any;
                readOnly?: boolean;
                writeOnly?: boolean;
                type?: import("@formily/json-schema").SchemaTypes;
                enum?: import("@formily/json-schema").SchemaEnum<any>;
                const?: any;
                multipleOf?: number;
                maximum?: number;
                exclusiveMaximum?: number;
                minimum?: number;
                exclusiveMinimum?: number;
                maxLength?: number;
                minLength?: number;
                pattern?: string | RegExp;
                maxItems?: number;
                minItems?: number;
                uniqueItems?: boolean;
                maxProperties?: number;
                minProperties?: number;
                required?: string | boolean | string[];
                format?: string;
                $ref?: string;
                $namespace?: string;
                definitions?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                properties?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                items?: import("@formily/json-schema").SchemaItems<any, any, any, any, any, any, any, any>;
                additionalItems?: import("@formily/json-schema").Stringify<any>;
                patternProperties?: import("@formily/json-schema").SchemaProperties<any, any, any, any, any, any, any, any>;
                additionalProperties?: import("@formily/json-schema").Stringify<any>;
                "x-value"?: any;
                "x-index"?: number;
                "x-pattern"?: any;
                "x-display"?: any;
                "x-validator"?: any;
                "x-decorator"?: any;
                "x-decorator-props"?: any;
                "x-component"?: any;
                "x-component-props"?: any;
                "x-reactions"?: import("@formily/json-schema").SchemaReactions<any>;
                "x-content"?: any;
                "x-data"?: any;
                "x-visible"?: boolean;
                "x-hidden"?: boolean;
                "x-disabled"?: boolean;
                "x-editable"?: boolean;
                "x-read-only"?: boolean;
                "x-read-pretty"?: boolean;
                "x-compile-omitted"?: string[];
            }>;
            "x-value"?: any;
            "x-index"?: number | (string & {});
            "x-pattern"?: any;
            "x-display"?: any;
            "x-validator"?: any;
            "x-decorator"?: any;
            "x-decorator-props"?: any;
            "x-component"?: any;
            "x-component-props"?: any;
            "x-reactions"?: (string & {}) | import("@formily/json-schema").SchemaReactions<any>;
            "x-content"?: any;
            "x-data"?: any;
            "x-visible"?: boolean | (string & {});
            "x-hidden"?: boolean | (string & {});
            "x-disabled"?: boolean | (string & {});
            "x-editable"?: boolean | (string & {});
            "x-read-only"?: boolean | (string & {});
            "x-read-pretty"?: boolean | (string & {});
            "x-compile-omitted"?: string[] | (string & {});
        };
        dataType: {
            type: string;
            title: string;
            'x-decorator': string;
            'x-component': string;
            'x-disabled': string;
            enum: {
                value: string;
                label: string;
            }[];
            required: boolean;
            default: string;
        };
        'uiSchema.x-component-props.step': {
            type: string;
            title: string;
            'x-component': string;
            'x-decorator': string;
            required: boolean;
            default: string;
            enum: {
                value: string;
                label: string;
            }[];
            'x-reactions': {
                dependencies: string[];
                fulfill: {
                    state: {
                        display: string;
                    };
                };
            }[];
        };
        'uiSchema.title': {
            type: string;
            title: string;
            required: boolean;
            'x-decorator': string;
            'x-component': string;
        };
        name: {
            type: string;
            title: string;
            required: boolean;
            'x-disabled': string;
            'x-decorator': string;
            'x-component': string;
            'x-validator': string;
            description: string;
        };
    };
    filterable: {
        operators: any[];
    };
    titleUsable: boolean;
}
